//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMedical.F.Views
{


    public partial class Weather
    {

        /// <summary>
        /// Control form1.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Control CityGrid.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView CityGrid;

        /// <summary>
        /// Control HiddenCity.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField HiddenCity;

        /// <summary>
        /// Control HiddenCondition.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField HiddenCondition;

        


    }
}
